name = "elchef-pages"
account_id = "YOUR_ACCOUNT_ID"
compatibility_date = "2024-11-12"

[pages]
# Cloudflare Pages project name
project_name = "elchef"
build_output_dir = ".vercel/output"

[vars]
# NEXT_PUBLIC_* are exposed to client automatically in Next
NEXT_PUBLIC_SUPABASE_URL = "${NEXT_PUBLIC_SUPABASE_URL}"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "${NEXT_PUBLIC_SUPABASE_ANON_KEY}"

# Server-side envs used in API routes
SUPABASE_URL = "${SUPABASE_URL}"
SUPABASE_SERVICE_ROLE_KEY = "${SUPABASE_SERVICE_ROLE_KEY}"
TELEGRAM_BOT_TOKEN = "${TELEGRAM_BOT_TOKEN}"
TELEGRAM_CHAT_IDS = "${TELEGRAM_CHAT_IDS}"
MAILERLITE_API_KEY = "${MAILERLITE_API_KEY}"
MAILERLITE_GROUP_ID = "${MAILERLITE_GROUP_ID}"
OPENAI_API_KEY = "${OPENAI_API_KEY}"
XAI_API_KEY = "${XAI_API_KEY}"

[[kv_namespaces]]
binding = "CRON_STATE"
id = ""

[[triggers.crons]]
# 09:00 Europe/Stockholm and midnight UTC daily equivalent windows
schedule = "0 7 * * *"

[build]
command = "npm run cf:build"

[observability]
enabled = true


